"""
Compilation script for the Causal-JEPA World Model.

Combines all Python source modules into a single importable file
for easy deployment on Kaggle or any environment where complex
package structures are inconvenient.

Usage:
    py -3.9 compile.py
    # Produces: causal_jepa.py
"""

import os
import re
import sys
from datetime import datetime


# Module files in strict dependency order.
# Each entry: (section_name, relative_path)
# ORDER MATTERS: dependencies must come before dependents.
SOURCE_MODULES = [
    ("Configuration",              "src/utils/config.py"),
    ("Logging Utilities",          "src/utils/logging.py"),
    ("Unified Encoder",            "src/model/encoder.py"),
    ("Causal Network",             "src/model/causal_net.py"),
    ("Memory System",              "src/model/memory.py"),
    ("Language Modeling Head",      "src/model/lm_head.py"),
    ("World Model Orchestrator",   "src/model/world_model.py"),
    ("Training Losses",            "src/training/losses.py"),
    ("EMA Scheduler",              "src/training/ema.py"),
    ("Trainer",                    "src/training/trainer.py"),
]

OUTPUT_FILE = "causal_jepa.py"


def is_relative_import(line: str) -> bool:
    """Check if a line is a relative import (any indentation level)."""
    return bool(re.match(r'\s*from\s+\.', line.strip()))


def process_module(filepath: str) -> str:
    """
    Read a module file and strip all relative imports.

    In the compiled single-file output, all symbols are in the same
    global namespace, so relative imports like `from .encoder import get_norm`
    become unnecessary — get_norm is already defined earlier in the file.
    """
    with open(filepath, "r", encoding="utf-8") as f:
        lines = f.readlines()

    processed = []
    for line in lines:
        # Strip relative imports at any indentation level
        if is_relative_import(line):
            # Replace with a comment so line numbers are roughly preserved
            indent = len(line) - len(line.lstrip())
            processed.append(" " * indent + "# [compiled-out relative import]")
            continue
        processed.append(line.rstrip("\n"))

    return "\n".join(processed)


def build():
    """Compile all source modules into a single file."""
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    header = f'''"""
Causal-JEPA World Model - Compiled Single-File Distribution
============================================================
Auto-generated by compile.py on {timestamp}
DO NOT EDIT THIS FILE DIRECTLY. Edit the source modules in src/ and recompile.

This file contains the complete Causal-JEPA architecture:
  - WorldModelConfig: Scalable configuration with 5 presets (13M-1.6B params)
  - UnifiedEncoder: Transformer backbone with RoPE, GQA, SwiGLU, flash attention
  - CausalStateCompressor: Attention-pooling to causal state vectors
  - CausalTransitionNetwork: Explicit state transition prediction
  - MemoryManager: FAISS episodic store + semantic concept graph
  - LanguageModelingHead: Weight-tied LM head with nucleus sampling
  - CausalWorldModel: Full model orchestrator with EMA target encoder
  - CausalWorldModelLoss: All 4 training losses (L_causal, L_cf, L_align, L_lm)
  - EMAScheduler: Cosine momentum annealing
  - CausalWorldModelTrainer: Complete training loop with AMP, gradient accumulation

Usage:
    from causal_jepa import WorldModelConfig, CausalWorldModel
    config = WorldModelConfig.base()
    model = CausalWorldModel(config)
"""
'''

    sections = []
    total_source_lines = 0

    for section_name, filepath in SOURCE_MODULES:
        if not os.path.exists(filepath):
            print(f"  WARNING: {filepath} not found, skipping")
            continue

        print(f"  Compiling: {filepath}")
        code = process_module(filepath)
        source_lines = len(code.split("\n"))
        total_source_lines += source_lines

        divider = "=" * 76
        section = f"""

# {divider}
#  {section_name}
#  Source: {filepath}
# {divider}

{code}
"""
        sections.append(section)

    # Write output
    with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
        f.write(header)
        for section in sections:
            f.write(section)

    # Stats
    with open(OUTPUT_FILE, "r", encoding="utf-8") as f:
        output_lines = sum(1 for _ in f)

    file_size = os.path.getsize(OUTPUT_FILE)
    print(f"\n  Output:    {OUTPUT_FILE}")
    print(f"  Modules:   {len(sections)}")
    print(f"  Lines:     {output_lines:,}")
    print(f"  Size:      {file_size / 1024:.1f} KB")


if __name__ == "__main__":
    print("=" * 60)
    print("  Causal-JEPA World Model - Build")
    print("=" * 60)
    build()
    print("\n  Build complete!")
    print("=" * 60)
